// Copyright © 2025–2026 Dankest, LLC
// Based on XChain Platform by Dankest, LLC – https://dankest.llc
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// This file is part of XChain Platform. Licensed under the GNU Affero
// General Public License v3.0 or later; see LICENSE.md. A commercial
// license (without AGPL source-disclosure terms) is available -
// contact legal@dankest.llc.
//
// Scaffold sources DRIFT + verdict guard.
//
// sdk.scaffold() returns sources embedded at build time (src/contract/templates.js,
// generated by scripts/sync-templates.js). They MUST stay byte-identical to the
// canonical xchain-contracts repo, or authors scaffold stale code. The drift guard
// (sha256 of the base64-decoded embed vs the canonical file) catches a stale embed.
// Skipped when the sibling xchain-contracts checkout is absent, and a hard failure
// instead under XCHAIN_REQUIRE_SIBLINGS=1.

const assert = require('assert');
const crypto = require('crypto');
const fs     = require('fs');
const path   = require('path');

const XChainSDK = require('../../../src/XChainSDK.js');
const EMBEDDED  = require('../../../src/contract/templates.js');

const SIBLING_ROOT  = process.env.XCHAIN_SIBLING_ROOT || path.join(__dirname, '../..', '..', '..');
const CONTRACTS_DIR = process.env.XCHAIN_CONTRACTS_DIR || path.join(SIBLING_ROOT, 'xchain-contracts');

// Throw where the sibling is required, skip elsewhere, so the drift guard can
// never green-by-skip in the job that checks xchain-contracts out.
const SIBLING_REQUIRED = process.env.XCHAIN_REQUIRE_SIBLINGS === '1';
function requireContracts(ctx) {
    if (fs.existsSync(CONTRACTS_DIR)) return true;
    if (SIBLING_REQUIRED)
        throw new Error('template drift guard cannot run: required sibling missing at ' + CONTRACTS_DIR +
            ' (the job setting XCHAIN_REQUIRE_SIBLINGS=1 must check out xchain-contracts)');
    ctx.skip();
    return false;
}

function sha256(buf) { return crypto.createHash('sha256').update(buf).digest('hex'); }
function canonicalTemplatePath(name) { return path.join(CONTRACTS_DIR, name, name + '.js'); }
function canonicalPatternPath(name)  { return path.join(CONTRACTS_DIR, 'patterns', name + '.js'); }

describe('scaffold sources: drift + verdict', function () {

    let sdk;
    before(function () { sdk = new XChainSDK({ network: 'bitcoin-regtest', noHub: true }); });

    describe('drift guard (embedded === canonical xchain-contracts)', function () {
        for (const name of Object.keys(EMBEDDED.templates)) {
            it('template ' + name + ' matches xchain-contracts/' + name + '/' + name + '.js', function () {
                if (!requireContracts(this)) return;
                const embedded  = Buffer.from(EMBEDDED.templates[name], 'base64');
                const canonical = fs.readFileSync(canonicalTemplatePath(name));
                assert.strictEqual(sha256(embedded), sha256(canonical),
                    'TEMPLATE DRIFT: ' + name + '; re-run `npm run sync:templates`.');
            });
        }
        for (const name of Object.keys(EMBEDDED.patterns)) {
            it('pattern ' + name + ' matches xchain-contracts/patterns/' + name + '.js', function () {
                if (!requireContracts(this)) return;
                const embedded  = Buffer.from(EMBEDDED.patterns[name], 'base64');
                const canonical = fs.readFileSync(canonicalPatternPath(name));
                assert.strictEqual(sha256(embedded), sha256(canonical),
                    'PATTERN DRIFT: ' + name + '; re-run `npm run sync:templates`.');
            });
        }
    });

    describe('sdk.scaffold() + listTemplates()', function () {
        it('lists the four templates and the patterns', function () {
            const l = sdk.listTemplates();
            for (const t of ['escrow', 'vesting', 'crowdsale', 'amm'])
                assert.ok(l.templates.includes(t), 'missing template ' + t);
            assert.ok(l.patterns.length > 0, 'expected patterns');
        });

        it('every scaffolded template is a non-empty string that passes validateContract', function () {
            for (const name of sdk.listTemplates().templates) {
                const src = sdk.scaffold(name);
                assert.strictEqual(typeof src, 'string');
                assert.ok(src.length > 0, name + ' is empty');
                assert.strictEqual(sdk.validateContract(src).valid, true,
                    name + ' failed validateContract: ' + JSON.stringify(sdk.validateContract(src).errors));
            }
        });

        it('every scaffolded pattern lints with zero errors', function () {
            for (const name of sdk.listTemplates().patterns) {
                const src = sdk.scaffold(name);
                const r = sdk.validateContract(src);
                assert.strictEqual(r.errors.length, 0, name + ' errors: ' + JSON.stringify(r.errors.map(e => e.rule)));
            }
        });

        it('an unknown name throws SDKContractError(TEMPLATE_NOT_FOUND)', function () {
            assert.throws(() => sdk.scaffold('does-not-exist'), function (e) {
                return e && e.code === 'TEMPLATE_NOT_FOUND';
            });
        });
    });

});
